name: smart_study_plan
description: 'A new Flutter project.'
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^9.1.1
  bloc: ^9.2.0
  equatable: ^2.0.5

  # Dependency Injection
  get_it: ^9.2.0

  # Local Storage
  hive: ^2.2.0
  hive_flutter: ^1.1.0

  # Firebase
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  cloud_firestore: ^6.1.1

  # Network & API
  dio: ^5.3.0
  connectivity_plus: ^7.0.0

  # Navigation
  go_router: ^17.0.1

  # UI & Design
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.0
  shimmer: ^3.0.0

  # Either/Result Pattern
  dartz: ^0.10.1

  # Background Tasks
  workmanager: ^0.9.0+3
  flutter_local_notifications: ^19.5.0

  # Utilities
  intl: ^0.20.2
  logger: ^2.1.0

  # Other
  uuid: ^4.0.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  bloc_test: ^10.0.0
  mocktail: ^1.0.0

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
