name: smart_study_plan
description: 'A new Flutter project.'
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  bloc: ^9.2.0
  cloud_firestore: ^6.1.1
  connectivity_plus: ^7.0.0
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dio: ^5.3.0
  equatable: ^2.0.5
  firebase_auth: ^6.1.3
  firebase_core: ^4.3.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_local_notifications: ^19.5.0
  flutter_svg: ^2.0.0
  get_it: ^9.2.0
  go_router: ^17.0.1
  google_fonts: ^6.1.0
  hive: ^2.2.0
  hive_flutter: ^1.1.0
  intl: ^0.20.2
  logger: ^2.1.0
  shimmer: ^3.0.0
  uuid: ^4.0.0
  workmanager: ^0.9.0+3

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.4.13
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  mocktail: ^1.0.0

flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
